/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeudasRouteImport } from './routes/deudas'
import { Route as MasRouteImport } from './routes/mas'
import { Route as MovimientosRouteImport } from './routes/movimientos'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeudasRoute = DeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimientosRoute = MovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deudas': typeof DeudasRoute
  '/mas': typeof MasRoute
  '/movimientos': typeof MovimientosRoute
  '/presupuesto': typeof PresupuestoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deudas': typeof DeudasRoute
  '/mas': typeof MasRoute
  '/movimientos': typeof MovimientosRoute
  '/presupuesto': typeof PresupuestoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deudas': typeof DeudasRoute
  '/mas': typeof MasRoute
  '/movimientos': typeof MovimientosRoute
  '/presupuesto': typeof PresupuestoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deudas' | '/mas' | '/movimientos' | '/presupuesto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deudas' | '/mas' | '/movimientos' | '/presupuesto'
  id: '__root__' | '/' | '/deudas' | '/mas' | '/movimientos' | '/presupuesto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeudasRoute: typeof DeudasRoute
  MasRoute: typeof MasRoute
  MovimientosRoute: typeof MovimientosRoute
  PresupuestoRoute: typeof PresupuestoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deudas': {
      id: '/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof DeudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimientos': {
      id: '/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof MovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeudasRoute: DeudasRoute,
  MasRoute: MasRoute,
  MovimientosRoute: MovimientosRoute,
  PresupuestoRoute: PresupuestoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
